@extends('layouts.app')

@section('title', $user->name . ' Profile')

@section('content')
    @include('users.profile.header')

    <div style="margin-top: 40px">

        {{-- AI Personality Summary --}}
        @if (isset($personalitySummary))
            <div class="ai-summary-box"
                style="background: #e6f0ff; padding: 20px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); margin-bottom: 30px;">
                <h5 style="font-weight: bold; font-size: 1.2rem; margin-bottom: 10px; color: #003366;">
                    🧠 Personality Insight Generated by AI
                </h5>
                <p style="font-size: 1rem; line-height: 1.6; color: #003366;">
                    Based on your posts and comment tone, here's how AI sees you:
                </p>
                <p style="font-size: 1.2rem; font-style: italic; color: #001a33; margin-top: 10px;">
                    “{{ $personalitySummary }}”
                </p>
            </div>
        @endif


        {{-- AI Tour Suggestion --}}
        @if (isset($recommendedTourLink))
            <div class="ai-tour-box"
                style="background: linear-gradient(to right, #e0f7fa, #e1f5fe); padding: 20px 24px; border-radius: 14px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06); margin-bottom: 35px;">

                <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap;">
                    <div style="flex: 1;">
                        <h5 style="font-size: 1.1rem; font-weight: 600; margin: 0 0 6px;">✨ Your Personalized Tour
                            Suggestion</h5>
                        <p style="font-size: 0.95rem; color: #555; margin: 0;">
                            🧭 Based on your interests and recent comments, AI predicts this tour may involve scenic
                            exploration, cultural immersion, or local experiences.
                        </p>
                    </div>

                    <a href="{{ $recommendedTourLink }}" target="_blank"
                        style="display: inline-flex; align-items: center; gap: 8px; background-color: #007bff; color: #fff; padding: 10px 18px; border-radius: 8px; font-weight: bold; font-size: 1rem; text-decoration: none; margin-top: 15px;">
                        GO TOUR
                        <i class="fa-solid fa-suitcase-rolling"></i>
                    </a>
                </div>
            </div>
        @endif

        {{-- Post Gallery --}}
        @if ($user->posts->isNotEmpty())
            <div class="row">
                @foreach ($user->posts as $post)
                    <div class="col-lg-4 col-md-6 mb-4 position-relative" data-post-id="{{ $post->id }}">
                        <a href="{{ route('post.show', $post->id) }}" class="d-block position-relative">
                            @php
                                $images = json_decode($post->image, true);
                            @endphp

                            @if (is_array($images))
                                <img src="{{ $images[0] }}" alt="post image" class="profile-grid-img">
                                <div class="multi-photo-icon">
                                    <i class="fa-solid fa-clone"></i>
                                </div>
                            @else
                                <img src="{{ $post->image }}" alt="post id {{ $post->id }}" class="grid-img">
                            @endif
                        </a>
                    </div>
                @endforeach
            </div>
        @else
            <h3 class="text-muted text-center">No Posts Yet</h3>
        @endif
    </div>
@endsection
