<style>
    .multi-photo-icon {
        position: absolute;
        top: 8px;
        right: 8px;
        background: rgba(0, 0, 0, 0.6);
        color: white;
        padding: 4px 6px;
        border-radius: 5px;
        font-size: 14px;
    }

    .grid-img {
        width: 100%;
        height: 230px;
        object-fit: cover;
        border-radius: 8px;
    }

    .ai-summary-box {
        margin-bottom: 30px;
        padding: 20px;
        background: linear-gradient(to right, #4b6cb7, #182848);
        color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
    }

    .ai-summary-box h5 {
        font-weight: bold;
        margin-bottom: 12px;
        color: #ffd700;
    }

    .ai-summary-box p {
        margin-bottom: 0;
        font-size: 1rem;
    }

    .ai-tour-box {
        padding: 20px;
        background: #f4f9ff;
        border-left: 5px solid #007bff;
        border-radius: 10px;
        margin-bottom: 35px;
        transition: box-shadow 0.3s ease;
    }

    .ai-tour-box:hover {
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1);
    }

    .ai-tour-box a {
        font-weight: bold;
        color: #007bff;
        text-decoration: underline;
    }
</style>

@extends('layouts.app')

@section('title', $user->name . ' Profile')

@section('content')
    @include('users.profile.header')

    <div style="margin-top: 40px">

        {{-- AI情報がある場合のみ表示 --}}
        @if (isset($personalitySummary))
            <div class="ai-summary-box">
                <h5>🧠 Personality Insight Generated by AI</h5>
                <p>
                    Based on your posts and comment tone, here's how AI sees you:<br>
                    <strong>{{ $personalitySummary }}</strong>
                </p>
            </div>
        @endif

        @if (isset($recommendedTourLink))
            <div class="ai-tour-box">
                <strong>✨ Your Personalized Tour Suggestion →
                    <a href="{{ $recommendedTourLink }}" target="_blank" style="display: inline-block; margin-top: 10px;">
                        <span style="font-size: 1.5rem; color: #007bff;">
                            GO TOUR
                            <i class="fa-solid fa-suitcase-rolling"></i>
                        </span>
                    </a>
                </strong>

                <p style="font-size: 0.95rem; color: #333; margin-top: 10px;">
                    🧭 Based on your interests and recent comments, AI predicts this tour may involve scenic exploration,
                    cultural immersion, or local experiences.
                </p>


            </div>
        @endif


        {{-- Post Gallery --}}
        @if ($user->posts->isNotEmpty())
            <div class="row">
                @foreach ($user->posts as $post)
                    <div class="col-lg-4 col-md-6 mb-4 position-relative">
                        <a href="{{ route('post.show', $post->id) }}" class="d-block position-relative">
                            @php
                                $images = json_decode($post->image, true);
                            @endphp

                            @if (is_array($images))
                                <img src="{{ $images[0] }}" alt="post image" class="grid-img">
                                <div class="multi-photo-icon">
                                    <i class="fa-solid fa-clone"></i>
                                </div>
                            @else
                                <img src="{{ $post->image }}" alt="post id {{ $post->id }}" class="grid-img">
                            @endif
                        </a>
                    </div>
                @endforeach
            </div>
        @else
            <h3 class="text-muted text-center">No Posts Yet</h3>
        @endif
    </div>
@endsection
